# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be1460ca9d10d6676c42831934099b35d23eb67f53dd74d186bb44fe682ac9775b311e0e2f7eb965176269ea2d3e0db62ffc083067392d24987fbacefdac8b1e

test:
  secret_key_base: 1bd0e02eabdc8cafb4a25dd90f395d457ea78cfa152f2d3ea53f56f1d4b352532376439033084460eef73667395f18ec9101d1757f6d1ab5e2e04c1d533f97b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
